### ISSUE TITLE
No question file in huggingface

### ISSUE THREAD

**Issue by Richar-Du** [eric-ai-lab/MMWorld#2]
Thanks for your awesome work! I am eager to use your benchmark to evaluate our model. However, when I downloaded the dataset from huggingface, there were only videos without any files with questions. Could you please share the file containing the test questions? Thanks in advance :)

**Comment by jkooy** [comment]
Hi, thanks for your interests!
The questions are also on the huggingface. You can find it in the dataset viewer.
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/aa1f1ae4-c621-4b3e-bf16-188c901537ab">


You can use 
```
curl -X GET \
     "https://datasets-server.huggingface.co/rows?dataset=Xuehai%2FMMWorld&config=default&split=eval&offset=0&length=100"
```
to access it.

For your convenience, I have now also uploaded the raw json file. You can find it here:
https://huggingface.co/datasets/Xuehai/MMWorld/blob/main/mmworld.json

Kindly let me know if you have further questions. Thank you.

**Comment by Richar-Du** [comment]
Great! Thanks for your kindly help :)
